### ISSUE TITLE
Read all example papers in order to get inspiration for our own paper

### ISSUE THREAD

**Issue by mmbc2008** [mmbc2008/Intelligent-Systems-Project#2]
This is a link to the papers on canvas that we were recommended to read. https://canvas.vu.nl/courses/49254/pages/some-papers-for-inspiration?module_item_id=483904

**Comment by cotrieo** [comment]
I spent today reading through the papers. In general there is a lot of differences to the approaches and methods used. However overall it seems once we have a good research questions and experiment idea it should become easy from then on out. Furthermore some literature research into our desired field of research is required. So I suggest we really try and come up with a set research question in tomorrow's meeting.

**Comment by mmbc2008** [comment]
I will try and look into some algorithm angles today around what we want to do. We can discuss some choices in whatsapp and I will bring some material I find to the standup tomorrow.
